# Generated by Django 3.2.7 on 2021-09-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='sold_at',
            field=models.DateTimeField(),
        ),
    ]
